spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://dev-db:5432/kafka_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  kafka:
    bootstrap-servers: dev-kafka:9092