spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url:  jdbc:h2:mem:kafkaproducerDB
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  kafka:
    bootstrap-servers: dev-kafka:9092